[build]
  command = "yarn build"
  publish = "public"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.thresholds]
    performance = 0.3
    accessibility = 0.8
    best-practices = 0.8
    seo = 0.8
    pwa = 0.8

[context.storybook]
  command = "yarn build-storybook"
  publish = "storybook-static"

[[context.storybook.plugins]]
  package = "@netlify/plugin-lighthouse"

  [context.storybook.plugins.inputs.thresholds]
    performance = 0
    accessibility = 0
    best-practices = 0
    seo = 0
    pwa = 0

[[redirects]]
  from = "/"
  to = "/en/"
  status = 302
  force = true

[[redirects]]
  from = '/*'
  to = '/index.html'
  status = 200