[build]
  command = "yarn build"
  publish = "public"
  functions = "server/functions"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.thresholds]
    performance = 0.2
    accessibility = 0.6
    best-practices = 0.6
    seo = 0.6
    pwa = 0.6

[[context.web3-login.plugins]]
  package = "@netlify/plugin-lighthouse"

  [context.web3-login.plugins.inputs.thresholds]
    performance = 0
    accessibility = 0
    best-practices = 0
    seo = 0
    pwa = 0

[[redirects]]
  from = '/api/*'
  to = '/.netlify/functions/api/:splat'
  status = 200

[[redirects]]
  from = "/app/*"
  to = "/app/index.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/archive/"
  status = 302
  force = true

[[redirects]]
  from = '/*'
  to = '/index.html'
  status = 200
