backend:
  name: git-gateway
  repo: efdevcon/devcon-website
  branch: feature-portal
  accept_roles:
    - admin
    - editor

slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '-'

local_backend: true
publish_mode: editorial_workflow
media_folder: static/assets/uploads/images
public_folder: /assets/uploads/images

i18n:
  structure: multiple_folders
  locales: [en, es]
  default_locale: en

collections:
  - name: 'pages'
    label: 'Pages'
    label_singular: 'Page'
    folder: 'src/content/pages'
    slug: '{{slug}}'
    create: true
    i18n: true
    fields:
      - { name: 'title', label: 'Title', widget: 'string', i18n: true }
      - { name: 'description', label: 'Description', widget: 'text', i18n: true, required: false }
      - { name: 'body', label: 'Body', widget: 'markdown', i18n: true }
      - {
          name: 'tags',
          label: 'Tags',
          widget: 'relation',
          i18n: 'duplicate',
          required: false,
          collection: 'tags',
          value_field: 'title',
          search_fields: ['title'],
          multiple: true,
        }
      - {
          name: 'template',
          label: 'Template',
          widget: 'select',
          i18n: 'duplicate',
          options: ['none', 'content', 'dips'],
          default: 'content',
        }
      - {
          name: 'parent',
          label: 'Parent',
          widget: 'relation',
          i18n: duplicate,
          required: false,
          collection: pages,
          value_field: '{{slug}}',
          search_fields: ['{{slug}}'],
        }
      - {
          name: 'order',
          label: 'Order',
          widget: 'number',
          i18n: 'duplicate',
          required: false,
          value_type: 'int',
          min: 1,
          max: 1000,
          step: 1,
        }
      - { name: 'showInMenu', label: 'Show page in Menu', widget: 'boolean', i18n: 'duplicate', default: true }
      - {
          name: 'translationVerified',
          label: 'If this translation has been (manually) verified',
          widget: 'boolean',
          i18n: 'duplicate',
          default: false,
        }

  - name: faq
    label: FAQ
    label_singular: FAQ
    folder: src/content/faq
    create: true
    i18n: true
    fields:
      - { name: title, label: Title, widget: string, i18n: true }
      - { name: body, label: Body, widget: markdown, i18n: true }
      - {
          name: category,
          label: Category,
          widget: relation,
          i18n: duplicate,
          collection: categories,
          value_field: title,
          search_fields: ['title'],
          multiple: true,
        }
      - {
          name: order,
          label: Order,
          widget: number,
          i18n: duplicate,
          required: false,
          value_type: int,
          min: 1,
          max: 1000,
          step: 1,
        }

  - name: categories
    label: Categories
    label_singular: Category
    folder: src/content/categories
    create: true
    i18n: true
    fields:
      - { name: title, label: Title, widget: string, i18n: true }

  - name: tags
    label: Tags
    label_singular: Tag
    folder: src/content/tags
    create: true
    i18n: true
    fields:
      - { name: title, label: Title, widget: string, i18n: true }

  - name: footer
    label: Footer
    files:
      - label: 'Footer settings'
        name: 'footer settings'
        file: src/content/footer/settings.md
        fields:
          - label: Highlighted links
            name: highlightedLinks
            widget: list
            types:
              - label: Page
                name: page
                fields:
                  - {
                      name: title,
                      label: Page,
                      search_fields: ['title'],
                      value_field: 'title',
                      widget: relation,
                      collection: pages,
                    }
              - label: URL
                name: url
                fields:
                  - { name: title, label: Title, widget: string }
                  - { name: url, label: URL, widget: string }
          - label: Left links
            name: leftLinks
            widget: list
            types:
              - label: Page
                name: page
                fields:
                  - {
                      name: title,
                      label: Page,
                      search_fields: ['title'],
                      value_field: 'title',
                      widget: relation,
                      collection: pages,
                    }
              - label: URL
                name: url
                fields:
                  - { name: title, label: Title, widget: string }
                  - { name: url, label: URL, widget: string }
          - label: Right links
            name: rightLinks
            widget: list
            types:
              - label: Page
                name: page
                fields:
                  - {
                      name: title,
                      label: Page,
                      search_fields: ['title'],
                      value_field: 'title',
                      widget: relation,
                      collection: pages,
                    }
              - label: URL
                name: url
                fields:
                  - { name: title, label: Title, widget: string }
                  - { name: url, label: URL, widget: string }
          - label: Bottom links
            name: bottomLinks
            widget: list
            types:
              - label: Page
                name: page
                fields:
                  - {
                      name: title,
                      label: Page,
                      search_fields: ['title'],
                      value_field: 'title',
                      widget: relation,
                      collection: pages,
                    }
              - label: URL
                name: url
                fields:
                  - { name: title, label: Title, widget: string }
                  - { name: url, label: URL, widget: string }
