name: Devcon CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: yarn

      - name: Run Prettier // Format
        run: yarn format

      - name: Run Eslint // Lint
        run: yarn lint

      - name: Run Build
        run: yarn build

      - name: Serve build to test against
        run: yarn serve &

      - uses: microsoft/playwright-github-action@v1

      - name: Run your tests
        run: npm test

      - uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: screenshots

      # - name: 'BrowserStack Env Setup'
      #   uses: 'browserstack/github-actions/setup-env@master'
      #   with:
      #     username: lassejacobsen2
      #     access-key: mBqtLq8ffDpp1UFA5679
      # build-name: 'BUILD_INFO'
      # project-name: 'REPO_NAME'

      # - name: 'Start BrowserStackLocal Tunnel'
      #   uses: 'browserstack/github-actions/setup-local@master'
      #   with:
      #     local-testing: 'start'
      #     local-logging-level: 'all-logs'
      #     local-identifier: 'random'

      # - name: Serve build to test against
      #   run: yarn browserstack

      # - name: 'Stop BrowserStackLocal'
      #   uses: 'browserstack/github-actions/setup-local@master'
      #   with:
      #     local-testing: 'stop'
