name: Devcon CI
on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}

      - name: Install dependencies
        run: yarn

      - name: Run Prettier // Format
        run: yarn format

      - name: Run Eslint // Lint
        run: yarn lint

      - name: Run Build
        run: yarn build

      - name: Serve build to test against
        run: yarn serve &

      - uses: microsoft/playwright-github-action@v1

      - name: Run your tests
        run: npm test

      - uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: screenshots
