name: Lighthouse CI for Netlify sites
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install & Build
        run: |
          yarn install
          yarn build

      - name: Run Lighthouse against a static dist dir
        uses: treosh/lighthouse-ci-action@v7
        with:
          configPath: './lighthouserc.json'